#cloud-config
package_update: true
packages:
  - golang
  - git
write_files:
  - path: /mnt/data/celestia/start.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      CELESTIA_CUSTOM='${celestia_custom}' /mnt/data/celestia/celestia-node/celestia bridge start --core.ip ${core_ip} --metrics --metrics.endpoint ${metrics_endpoint} --node.store /mnt/data/celestia-bridge

runcmd:
  - echo "Detecting and formatting the correct volume"
  - |
    volume_size_mb=$(( ${volume_size} * 1024 * 1024 * 1024 ))
    correct_device=$(lsblk -b -o NAME,SIZE -d | awk -v size=$volume_size_mb '$2 == size {print $1}' | head -n 1)
    if [ -n "$correct_device" ]; then
      mkfs.ext4 /dev/$correct_device
      mkdir -p /mnt/data
      mount /dev/$correct_device /mnt/data
    else
      echo "No volume of the expected size ${volume_size}G found."
      exit 1
    fi
  - apt-get update
  - apt-get install -y wget
  - export HOME=/root
  - mkdir -p /mnt/data/celestia/celestia-node
  - wget https://github.com/celestiaorg/celestia-app/releases/download/v1.12.0/celestia-app_Darwin_x86_64.tar.gz -O /mnt/data/celestia/celestia-app.tar.gz
  - tar -xzf /mnt/data/celestia/celestia-app.tar.gz -C /mnt/data/celestia/celestia-app
